mv ./draw-4sliders/draw-4sliders.py ./draw-4sliders/draw-4sliders.py
mv ./draw-etchafont/draw-etchafont.py ./draw-etchafont/draw-etchafont.py
mv ./draw-spotlight/draw-spotlight.py ./draw-spotlight/draw-spotlight.py
mv ./notes-basic/notes-basic.py ./notes-basic/notes-basic.py
mv ./scope-ballslines/basic-h-scope.py ./scope-ballslines/scope-ballslines.py
mv ./scope-circular/CIRCULAR-1.py ./scope-circular/scope-circular.py
mv ./scope-circular-ballslines/circle-balls-with-lines.py ./scope-circular-ballslines/scope-circular-ballslines.py
mv ./scope-concentric/coencentric.py ./scope-concentric/scope-concentric.py
mv ./scope-connected-centered/h-scope-connected.py ./scope-connected-centered/scope-connected-centered.py
mv ./scope-first-math/little-math.py ./scope-first-math/scope-first-math.py
mv ./scope-football/h-scope-wow-cool.py ./scope-football/scope-football.py
mv ./scope-fun/funtimes.py ./scope-fun/scope-fun.py
mv ./scope-gradient/basic-scope-bw.py ./scope-gradient/scope-gradient.py
mv ./scope-image/colored-grabs.py ./scope-image/scope-image.py
mv ./scope-lines-offset/basic-scope2.py ./scope-lines-offset/scope-lines-offset.py
mv ./scope-squares/basic-scope.py ./scope-squares/scope-squares.py
mv ./scope-vlines/basci-scope-3.py ./scope-vlines/scope-vlines.py
mv ./trig-alpha-test/ImageAlphaTest.py ./trig-alpha-test/trig-alpha-test.py
mv ./trig-balls/basic-rhy-scope.py ./trig-balls/trig-balls.py
mv ./trig-circle-with-image/treefill.py ./trig-circle-with-image/trig-circle-with-image.py
mv ./trig-circlemask/masktest.py ./trig-circlemask/trig-circlemask.py
mv ./trig-circlemask/satestest.py ./trig-circlemask/trig-circlemask.py
mv ./trig-fonts/symbol-random.py ./trig-fonts/trig-fonts.py
mv ./trig-fontzoomer/fontzoomer.py ./trig-fontzoomer/trig-fontzoomer.py
mv ./trig-fullpies/serious-pies.py ./trig-fullpies/trig-fullpies.py
mv ./trig-imagezoomer/flower-scope.py ./trig-imagezoomer/trig-imagezoomer.py
mv ./trig-pieplate/pieplate.py ./trig-pieplate/trig-pieplate.py
mv ./trig-slideshow/simple-slideshow.py ./trig-slideshow/trig-slideshow.py
mv ./trig-squares/squares.py ./trig-squares/trig-squares.py
mv ./trig-symbol-fg-persist/fgbg-test.py ./trig-symbol-fg-persist/trig-symbol-fg-persist.py
mv ./trig-traps/p2.py ./trig-traps/trig-traps.py
mv ./trig-windows/windows.py ./trig-windows/trig-windows.py
